{{- if and .Values.kubescapeStorage.enabled .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kubescapeStorage.apiServer.deploymentName" . | quote }}
  namespace: {{ .Values.ksNamespace }}
  labels:
    {{ .Values.kubescapeStorage.k8sApiserver.deployment.labels | toYaml  | nindent 4}}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size.backingStorage }}
  {{- if ne .Values.persistence.storageClass "-" }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
