{{- $components := fromYaml (include "components" .) }}
  {{- if $components.operator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.ksNamespace }}
data:
  config.json: |
    {
        "namespace": "{{ .Values.ksNamespace }}",
        "triggersecurityframework": {{ .Values.operator.triggerSecurityFramework }}
    }
  matchingRules.json: |
    {
    	"match": [
    		{
    			"apiGroups": ["apps"],
    			"apiVersions": ["v1"],
    			"resources": ["deployments"]
    		}
    	],
    	"namespaces": ["kube-system", "default"]
    }
{{- end }}
