{{- if and (eq (include "relevancy.Enabled" .) "true") .Values.storage.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.ClusterRoleBinding }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.nodeAgent.ServiceAccount }}
  namespace: {{ .Values.ksNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.nodeAgent.ClusterRole }}
{{- end}}