{{- if and .Values.nodeAgent.enabled .Values.kubescapeStorage.enabled }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.nodeAgent.ClusterRole }}
  namespace: {{ .Values.ksNamespace }}
rules:
- apiGroups: ["spdx.softwarecomposition.kubescape.io"]
  resources: ["sbomspdxv2p3s"]
  verbs: ["create", "get", "update"]
{{- end}}