{{- if and (eq (include "relevancy.Enabled" .) "true") .Values.storage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeAgent.ServiceAccount }}
  namespace: {{ .Values.ksNamespace }}
{{- end}}