{{- if and .Values.nodeAgent.enabled .Values.storage.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nodeAgent.ServiceAccount }}
  namespace: {{ .Values.ksNamespace }}
{{- end}}